### ISSUE TITLE
missing 'Wiring diagram'

### ISSUE THREAD

**Issue by Trigger-broom-289** [dokeeffe/indi-aldiroof#1]
Hello,

Thanks for adding the "scope park aware feature".
I see that you are using 4 relays, why 4 please?
Are you able also to provide the wiring diagram please?

on a side note, check out my feedback about the "scope park aware feature".
http://www.indilib.org/forum/ekos/1598-feedback-for-the-new-feature-scope-park-aware.html

thanks
Stephane

**Comment by Trigger-broom-289** [comment]
I believe I know why you're using 4 relays, the motor is AC, switch is a pendent one.
Found the wiring diagram in the following post:
http://forum.arduino.cc/index.php?topic=142236.0

**Comment by dokeeffe** [comment]
Hi Stephane,

Yes, I really need to add that wiring diagram :-) Let me think it through as I write and it might refresh my memory too... I used an electric hoist/winch that I bought in Aldi. It had a manual hand control with a heavy duty (30A) 3 way switch. Middle=off, Up=wind-out, Down=wind-in. So I took the hand control apart and found 6 wires coming out of this switch!! Took me a while to figure it out but for 6 wires I needed 4 relays for both directions... I'll draw it on paper now and upload later to the repo.
Derek

**Comment by dokeeffe** [comment]
BTW I think your box observatory is great. I wish I built something like that instead of the one I built.. :-)

**Comment by Trigger-broom-289** [comment]
Thanks Derek, I'm rebuilding it at the moment. More compact, mini roll on roof mounted on telescoping rails, new electronic (keeping the Odroid C1) etc...

I would like to use your driver 'indi-aldiroof' for my roll on roof, however I will be controlling a DC motor and only need two relays.
Wiring similar to the following:
http://www.midikits.net/midi_linear_actuator/relay_connections.JPG
Any chance your driver could be modified to achieve this if possible please?
Sadly I'm not good at developing stuff at all :(

**Comment by dokeeffe** [comment]
Are you also using an arduino? My driver talks to an arduino over USB to switch on/off the relays. You could use the exact same driver and arduino firmware and just wire 2 relays to the arduino. This should work.

**Comment by Trigger-broom-289** [comment]
Yes I will be using an arduino, I guess I can use your code as it is and as you said only use 2 relays.
Will let you know if I encounter any issues. thanks for the help.

**Comment by dokeeffe** [comment]
No problem, hope I can help. BTW if you can use 30A relays. Well it depends on your motor. I tried the cheap 10A relays first and they got fried. Those 220v electric hoists have a large initial start current. Maybe you will be ok with a DC motor though.

**Comment by dokeeffe** [comment]
Sorry bit of a delay,,, I'm away this weekend so it will be Tuesday :-( sorry about that

**Comment by dokeeffe** [comment]
Added, hope its some help

**Comment by Trigger-broom-289** [comment]
Thanks for posting the diagram, very helpful.

**Comment by astrolivier76** [comment]
Hello,

I would like to do what Trigger-broom-289 maked, that is to say use a DC motor with 2 relays.
Can you help me please? I am a beginner!
with a drawing where to connect the DC motor if possible :)

for information, I will use a nano arduino.

sincerely.

Olivier

**Comment by dokeeffe** [comment]
Hi Oliver, I think its not possible to switch a DC motor direction with just 2 relays. 
Basically you have 2 wires in the DC motor, + and -, to switch direction you need to swap these 2 wires. To swap polarity I cant picture a way to do this with just 2 relays.

**Comment by astrolivier76** [comment]
Hi,

thanks for the response. If I use 4 relays, your drawing is the same? Because i will not use the yellow remote control like you.
are you ok to make a drawing just for me with the wires (and the 4 relays) to use your arduino code and use the indi driver for my installation with a dc motor.

Thanks a lot, have a nice day,

Olivier

**Comment by astrolivier76** [comment]
PS: I don't see where i must to connect the two wires of the dc motor on the 4 relays!

Olivier

**Comment by dokeeffe** [comment]
Can you email me directly and I'll draw one in paper derek0207@gmail.com

**Comment by astrolivier76** [comment]
Thanks,

my email is:

alonso.o76@gmail.com

I respond you direcly on your mail, and i hope to don't disturb you.

Olivier
