### ISSUE TITLE
resistor value?

### ISSUE THREAD

**Issue by Trigger-broom-289** [dokeeffe/indi-aldiroof#3]
Not really an issue, what are the values of the resistors used for the limit switches please?

Stephane

**Comment by dokeeffe** [comment]
Its a 10K resistor. Its common to use a resistor like this for buttons / switches. Known as a pull up/pull down I followed this guide to figure out how to wire up switches  https://www.arduino.cc/en/tutorial/button

**Comment by Trigger-broom-289** [comment]
Thanks, I had found some articles online but with different values.
I'll pop to the local store tomorrow and get a few 10k.
